### ISSUE TITLE
Bot crashes when updating the status

### ISSUE THREAD

**Issue by Conorjames98** [emilkrebs/Nitrado-Bot#3]
Be sure to run "npm install -g typescript" in the root <nitrado-bot>

**Comment by emilkrebs** [comment]
Yeah, forgot to add that in the README.md file. Thanks! Should I add it or do you want to add it yourself?

**Comment by emilkrebs** [comment]
When you run `npm i` inside of the project directory it should also install `typescript` for the project but not globally.

**Comment by Conorjames98** [comment]
You can add it unfortunately still haven't got it working, it just updates status and then get a connection error it's a bit or miss if it even tells me how many players are online.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Conorjames98** [comment]
And yeah npm I didn't install anything I had to install

Discord.js colors.

And also had to run --save-dev @types/node-fetch for type declaration.

**Comment by emilkrebs** [comment]
When I follow the README everything works fine. What node version are you using and how can I replicate this issue?

**Comment by emilkrebs** [comment]
I sadly can't test the bot currently because I don't have any Nitrado service running

**Comment by Conorjames98** [comment]
[18:42:24] Bot is Ready.
[18:42:24] Bot is logged in as Arkitekx AI#5099.
[18:42:24] Bot is running on 2 servers.
[18:42:24] --------------------------------------------------
[18:42:24] Starting Nitrado API Ping...
[18:42:24] Ping to Nitrado API was successful.
[18:42:24] Updating status...
[18:42:26] Server started with 11 players online.
[18:42:36] Updating status...
[18:42:54] Server started with 11 players online.
[18:43:4] Updating status...
[18:43:13] Server started with 11 players online.
[18:43:23] Updating status...


and it continues to do this until it fails to connect I was wondering is there a need for the repeated updating status?

**Comment by emilkrebs** [comment]
It repeats to update the status so you can view the number of players playing on the server on the bots status.

**Comment by emilkrebs** [comment]
https://github.com/emilkrebs/Nitrado-Bot/blob/f886ce5f8a65abcceec1dbec2876f59004893de8/src/index.ts#L43

this line controls the updating delay (currently 10s)

**Comment by Conorjames98** [comment]
Oh for some reason after three or four attempts it sadly fails and the error is fatal

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by emilkrebs** [comment]
What error message do you get?

**Comment by Conorjames98** [comment]
ETIMEDOUT Fetch error

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by emilkrebs** [comment]
Does it provide any error code like `504`?

**Comment by Conorjames98** [comment]
Now I'm getting ECONRESET and no there isn't.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by emilkrebs** [comment]
It seems like NitrAPI has some limitations which don't get handled.

**Comment by Conorjames98** [comment]
It's annoying to say the least.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by emilkrebs** [comment]
Yes, maybe turn off the status updates for now. I can't fix it currently but I am open if you have any suggestions for fixing this problem.

**Comment by Conorjames98** [comment]
I'll take a look, I've just added error handling so it doesn't terminate the application for now

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by emilkrebs** [comment]
Thats nice! You could push your changes into a separate branch and create a Pull Request.

**Comment by Conorjames98** [comment]
Yeah it's probably an issue with the API I've never had any issues like this with other tokens it's even failing the health check sometimes now.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Conorjames98** [comment]
Hit or miss really lol

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Conorjames98** [comment]
But got it working pretty much with error handling and changing the interval of the player status to 10 mins it's not restarted one of my ark servers.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Conorjames98** [comment]
if anyone else has the same issue when the api fails to connect every 10 seconds change line 43 to     


setTimeout(scheduleAsync, 200000);

this will only update players every 10 minutes. (alternatively add error handling so the bot doesn't terminate the program.) 

it's important to note that my connection might not be perfect and this could be an issue unique to me but nonetheless the solution worked for me.
